### ISSUE TITLE
Make audio/video work on OS X

### ISSUE THREAD

**Issue by dvor** [dvor/objcTox#120]
Platform dependent should be wrapped to

``` objc
#if TARGET_OS_IPHONE
    // do iOS stuff
#else
    // do OS X stuff
#endif
```

However this should be avoid if possible. For example `UIView` can be replaced with `OCTView`, which would be typedef'd to `UIView` or `NSView` somewhere in the code.

**Comment by stal888** [comment]
Maybe OCTAudioEngine and OCTVideoEngine should be made user-serviceable (as in file conduits)?
We could provide separate iOS and OS X implementations without a lot of preprocessor stuff.

**Comment by dvor** [comment]
It depends on how much common code they both have. For example if you'll look at AudioEngine, all code it has is suitable for both iOS and OS X, differences are in
- creating image from pixels buffer [here](https://github.com/Antidote-for-Tox/objcTox/blob/audio/Classes/Private/Manager/Video/OCTVideoEngine.m#L268-L272)
- orientation change (which is only iOS specific) [here](https://github.com/Antidote-for-Tox/objcTox/blob/audio/Classes/Private/Manager/Video/OCTVideoEngine.m#L393-L435).

So there would be just 2 macros for whole engine which is not that bad.

**Comment by dvor** [comment]
Done
