### ISSUE TITLE
Investigate OS X project on Xcode 7

### ISSUE THREAD

**Issue by dvor** [dvor/objcTox#126]
vpx isn't building there

> ld: in /Volumes/stal/objcTox/Pods/toxcore/vpx.framework/vpx(vpx_decoder.c.o), building for OSX, but linking in object file built for iOS, for architecture x86_64

**Comment by Chuongv** [comment]
Weird, this is only for Xcode 7? Not Xcode 6?

**Comment by dvor** [comment]
Yes. Well, we are building vpx with iosbuild script. It's strange that it compiles for OS X too :-)
