### ISSUE TITLE
Use an in-memory Realm for tests

### ISSUE THREAD

**Issue by Chuongv** [dvor/objcTox#132]
Currently in `OCTRealmTests`, we are writing to disk to create a realm file for testing. I think it would be better to use an in-memory realm, like so https://realm.io/docs/objc/latest/#testing

Since we are using realm 0.94, we would use `+[RLMRealm inMemoryRealmWithIdentifier:]`

**Comment by dvor** [comment]
Currently we're using 0.93. Need to migrate first
https://github.com/Antidote-for-Tox/objcTox/issues/133
