### ISSUE TITLE
OCTSubmanagerCalls, send cancel call control in dealloc

### ISSUE THREAD

**Issue by Chuongv** [dvor/objcTox#159]
It would beneficial to send a call control cancel to all calls prior to being dealloc. Currently if we just kill toxav, no notification is sent to peers*.

Related to https://github.com/Antidote-for-Tox/objcTox/issues/154

*https://github.com/irungentoo/toxcore/blob/master/toxav/toxav.h#L199

**Comment by Chuongv** [comment]
@dvor Do you know a good way I can send a cancel call control to all calls from `OCTSubmanagerCalls`? I was going to originally going to add a public method in `OCTRealmManager` to return `RLMResults` of all the calls. That way `OCTSubmanagerCalls` can just iterate over that container. But I'm not sure if that is something that `OCTSubmanager` should have access to? Perhaps I am over thinking this?

**Comment by dvor** [comment]
I think you can use `- (RBQFetchRequest *)fetchRequestForClass:(Class)class withPredicate:(NSPredicate *)predicate;` method of `OCTRealmManager` and then get all calls from fetch request.

**Comment by dvor** [comment]
Also you can check [this](https://github.com/Antidote-for-Tox/objcTox/blob/ac32e2ba84c037988c635f5af11d06061b488337/Classes/Private/Manager/Database/OCTRealmManager.h#L59) method from file-transfer branch. Probably you can copy it from there.

**Comment by dvor** [comment]
Fixed
