### ISSUE TITLE
Sync methods on RealmManager may lead to deadlock

### ISSUE THREAD

**Issue by dvor** [dvor/objcTox#51]
Need to investigate this.

**Comment by Chuongv** [comment]
So I was looking at this today. In Antidote, all the the `RBQFetchedResultsControllerDelegate` methods are ran on the `OCTRealmManager` queue. So when we call a method that does any realm work (for example in Antidote `updateLastReadDate`) it dispatch_sync on the same queue again which causes a deadlock. I'm not sure if we could do anything on the objcTox side of things to alleviate this.

**Comment by dvor** [comment]
Yeah, this doesn't look good. One option is to modify RBQ controller. Other is to wait for Realm https://github.com/realm/realm-cocoa/issues/687

**Comment by bigfish24** [comment]
Just noticed this from the link to the Realm issue. While Realm is getting close to having the feature support to make RBQFRC irrelevant, I can hopefully help with RBQFRC in the mean time. The deadlock issue is expected (and listed as a limitation in the [README](https://github.com/Roobiq/RBQFetchedResultsController)). You should make sure that every write that triggers a notification for RBQFRC is on a background thread.

**Comment by dvor** [comment]
Hi @bigfish24, thanks for answering. I'll give that a try.

**Comment by dvor** [comment]
No longer relevant after migrating to Realm notifications.
