### ISSUE TITLE
OCTCall refactoring

### ISSUE THREAD

**Issue by dvor** [dvor/objcTox#55]
To be consistent with other classes it would be nice to
- rename `callDuration` to `callDurationInterval`
- add `- (NSDate *)callDuration;` method.

See [OCTMessageAbstract](https://github.com/Antidote-for-Tox/objcTox/blob/master/Classes/Public/Manager/Objects/OCTMessageAbstract.h#L27) as an example.

**Comment by Chuongv** [comment]
The `- (NSDate *)callDuration;` is a little confusing to me. Is this meant to give you the date when the call started?

**Comment by dvor** [comment]
Oops. Sorry, I was completely wrong %) Don't know why I was so confused about this interval.

Also forget about related comments in the pull request. Sorry. :-)

**Comment by dvor** [comment]
This is really strange, I was completely sure it was some date, not duration %)
